### Hello Client
GET  {{host}}/clients

### Client 생성 요청
POST {{host}}/client/register
Content-Type: application/json

{
  "name": "청와대 공식 키",
  "email": "webmaster@president.go.kr",
  "issuerInfo": "청와대",
  "allowedIps": [
    "127.0.0.1",
    "1.227.0.0.1",
    "242.101.0.1"
  ]
}
