### Variables
@host = http://localhost:8081
@contentType = application/json
@id = c47ccf98-ad70-4c3d-be82-86e485cc9535
@apiKey = VbyuCkHd-fcygWhWwCao5lbhd_VDO0CNLcNFdwsXseA

### Hello Client
GET {{host}}/clients

### Client 성공 케이스
POST {{host}}/clients
Content-Type: {{contentType}}

{
    "name": "A청와대 공식 키",
    "email": "Awebmaster@president.go.kr",
    "issuerInfo": "청와대",
    "allowedIps": ["127.0.0.1", "1.227.0.0.1", "242.101.0.1","*"]
}


### 랜덤 클라이언트 생성
POST {{host}}/clients/random

###  클라이언트 정보 조회
GET {{host}}/clients/{{id}}

###  클라이언트 정보 조회 A
GET {{host}}/api/A
X-API-KEY: {{apiKey}}

###  클라이언트 정보 조회 B
GET {{host}}/api/B
X-API-KEY: {{apiKey}}
