spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL:jdbc:postgresql://localhost:5432/postgres}
    username: ${DB_USER:local_postgres}
    password: ${DB_PASSWORD:local_postgres}
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate

  # p6spy 설정 추가
  sleuth:
    jdbc:
      p6spy:
        tracing:
          include-parameter-values: true

decorator:
  datasource:
    p6spy:
      enable: true
      enable-logging: true
      multiline: true
      logging: slf4j

logging:
  level:
    root: info
    org.hibernate.SQL: off
    org.hibernate.type.descriptor.sql.BasicBinder: off
    p6spy: debug
